/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },

    extend: {
      fontFamily: {
        rubik: ["Rubik", "sans-serif"],
        nunito: ["Nunito", "sans-serif"],
      },

      /* colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brand: {
          orange: "#ffa58d",
          darkOrange: "#d66f76",
          violet: "#ad59ad",
          darkViolet: "#913c91",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      }, */
      colors: {
        "primary/50": "#f7eef7",
        "primary/100": "#e6cce6",
        "primary/200": "#d9b3d9",
        "primary/300": "#c890c8",
        "primary/400": "#bd7abd",
        "primary/500": "#ad59ad",
        "primary/600": "#9d519d",
        "primary/700": "#7b3f7b",
        "primary/800": "#5f315f",
        "primary/900": "#492549",
        "secondary/33": "#fff6f4",
        "secondary/100": "#ffe3dc",
        "secondary/200": "#ffd6cb",
        "secondary/300": "#ffc3b3",
        "secondary/400": "#FFB7A4",
        "secondary/500": "#ffa58d",
        "secondary/600": "#e89680",
        "secondary/700": "#b57564",
        "secondary/800": "#8c5b4e",
        "secondary/900": "#6b453b",
        "dark-secondary-50": "#fbf1f1",
        "dark-secondary-100": "#f3d2d5",
        "dark-secondary-200": "#edbcc0",
        "dark-secondary-300": "#e49ea3",
        "dark-secondary-400": "#df8b91",
        "dark-secondary-500": "#d76e76",
        "dark-secondary-600": "#c4646b",
        "dark-secondary-700": "#994e54",
        "dark-secondary-800": "#763d41",
        "dark-secondary-900": "#5a2e32",
        "heading-50": "#e7e8ea",
        "heading-100": "#b4b7bd",
        "heading-200": "#90949d",
        "heading-300": "#5e6470",
        "heading-400": "#3e4554",
        "heading-500": "#0e1729",
        "heading-600": "#0d1525",
        "heading-700": "#0a101d",
        "heading-800": "#080d17",
        "heading-900": "#060a11",
        "default text-50": "#e9eaeb",
        "default text-100": "#bbbdc2",
        "default text-200": "#9a9da5",
        "default text-300": "#6c707c",
        "default text-400": "#4f5562",
        "default text-500": "#232a3b",
        "default text-600": "#202636",
        "default text-700": "#191e2a",
        "default text-800": "#131720",
        "default text-900": "#0f1219",
        "dark-primary-50": "#f4ecf4",
        "dark-primary-100": "#ddc3dd",
        "dark-primary-200": "#cca5cc",
        "dark-primary-300": "#b57cb5",
        "dark-primary-400": "#a763a7",
        "dark-primary-500": "#913c91",
        "dark-primary-600": "#843784",
        "dark-primary-700": "#672b67",
        "dark-primary-800": "#502150",
        "dark-primary-900": "#3d193d",
      },
      /* borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      }, */
      borderRadius: {
        "rounded-0": "0rem",
        "rounded-1": "0.01875000074505806rem",
        "rounded-2": "0.125rem",
        "rounded-3": "0.1875rem",
        "rounded-4": "0.25rem",
        "rounded-5": "0.3125rem",
        "rounded-6": "0.375rem",
        "rounded-7": "0.4375rem",
        "rounded-8": "0.5rem",
        "rounded-9": "0.625rem",
        "rounded-10": "0.75rem",
        "rounded-11": "0.9375rem",
        "rounded-12": "1.1875rem",
        "rounded-13": "1.25rem",
        "rounded-14": "1.8125rem",
        "rounded-15": "2.5rem",
        "rounded-16": "2.90625rem",
        "rounded-17": "3.125rem",
        "rounded-18": "6rem",
        "rounded-19": "62.4375rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
